CREATE DATABASE pessoas;

USE pessoas;

CREATE TABLE Pessoas
(
	idPessoa	TINYINT	PRIMARY	KEY	IDENTITY
	,Nome		VARCHAR(100) NOT NULL
);

CREATE TABLE Emails
(
	idEmail		TINYINT	PRIMARY	KEY	IDENTITY
	,idPessoa	TINYINT	FOREIGN	KEY	REFERENCES Pessoas (idPessoa)
	,Email		VARCHAR(100) NOT NULL
);

CREATE TABLE Telefones
(
	idTelefone	TINYINT	PRIMARY	KEY	IDENTITY
	,idPessoa	TINYINT	FOREIGN	KEY	REFERENCES Pessoas (idPessoa)
	,Telefone	VARCHAR(100) NOT NULL
);

CREATE TABLE CNHs
(
	idCNHs		TINYINT	PRIMARY	KEY	IDENTITY
	,idPessoa	TINYINT	FOREIGN	KEY	REFERENCES	Pessoas	(idPessoa)
	,CNH		VARCHAR(100) NOT NULL
);