CREATE DATABASE locadora;

USE locadora;

CREATE TABLE Empresas
(
	idEmpresa	TINYINT	PRIMARY	KEY	IDENTITY
	,Nome		VARCHAR(100) NOT NULL
);

CREATE TABLE Veiculos
(
	idVeiculo	TINYINT	PRIMARY KEY	IDENTITY
	,idEmpresa	TINYINT	FOREIGN	KEY REFERENCES	Empresas (idEmpresa)
	,idModelo	TINYINT	FOREIGN	KEY REFERENCES	Modelos (idModelo)
	,Placa		VARCHAR(10)	NOT NULL
);

CREATE TABLE Marcas
(
	idMarca	TINYINT	PRIMARY KEY IDENTITY
	,Nome	VARCHAR(100) NOT NULL
);

CREATE TABLE Clientes
(
	idCliente	TINYINT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(100) NOT NULL
	,CPF		VARCHAR(100) NOT NULL
);

CREATE TABLE Modelos
(
	idModelo	TINYINT PRIMARY KEY IDENTITY
	,idMarca	TINYINT FOREIGN KEY REFERENCES Marcas (idMarca)
	,Modelo		VARCHAR(100) NOT NULL
);

CREATE TABLE Alugueis
(
	idAluguel	TINYINT PRIMARY KEY IDENTITY
	,idCliente	TINYINT FOREIGN KEY REFERENCES Clientes (idCliente)
	,idVeiculo	TINYINT FOREIGN KEY REFERENCES Veiculos (idVeiculo)
	,DataInicio	SMALLDATETIME NOT NULL
	,DataFim	SMALLDATETIME	  NOT NULL
);