CREATE DATABASE	pclinics;

USE	pclinics;

CREATE TABLE Clinicas
(
	idClinica		TINYINT	PRIMARY KEY IDENTITY
	,RazaoSocial	VARCHAR(100) NOT NULL
	,CNPJ			VARCHAR(100) NOT NULL
	,Endereco		VARCHAR(100) NOT NULL
);

CREATE TABLE TiposPets
(
	idTipoPet	TINYINT PRIMARY KEY IDENTITY
	,Decricao	VARCHAR(100) NOT NULL
);

CREATE TABLE Racas
(
	idRaca		TINYINT PRIMARY KEY IDENTITY
	,idTipoPet	TINYINT FOREIGN KEY REFERENCES TiposPets (idTipoPet)
	,Descricao	VARCHAR(100) NOT NULL
);

CREATE TABLE Pets
(
	idPet			 TINYINT PRIMARY KEY IDENTITY
	,idRaca			 TINYINT FOREIGN KEY REFERENCES Racas (idRaca)
	,idDono			 TINYINT	FOREIGN KEY REFERENCES Donos (idDono)
	,Nome			 VARCHAR(100) NOT NULL
	,DataNascimento	 DATE NOT NULL
);

CREATE TABLE Atendimentos
(
	idAtendimento		TINYINT	PRIMARY KEY IDENTITY
	,idVeterinario		TINYINT FOREIGN KEY REFERENCES Veterinarios (idVeterinario)
	,idPet				TINYINT FOREIGN KEY REFERENCES	Pets (idPet)
	,DataAtendimento	DATE NOT NULL
	,Descricao			VARCHAR(500) NOT NULL
);

CREATE TABLE Donos
(
	idDono	TINYINT PRIMARY KEY IDENTITY
	,Nome	VARCHAR(100) NOT NULL
);

CREATE TABLE Veterinarios
(
	idVeterinario	TINYINT PRIMARY KEY IDENTITY
	,idClinica		TINYINT FOREIGN KEY REFERENCES Clinicas (idClinica)
	,Nome			VARCHAR(100) NOT NULL
	,CRMV			VARCHAR(100) NOT NULL
);